server:
  port: 8080 # The standard entry port for the outside world

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Automatically create routes based on Eureka Service IDs
          lower-case-service-id: true

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10 # Send heartbeat every 10 second (Default: 30s)
    lease-expiration-duration-in-seconds: 30 # If you don't hear from me in 30 seconds, kill me (Default: 90s)

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /v3/api-docs/auth-service
      - name: Order Service
        url: /v3/api-docs/order-service
      - name: Wallet Service
        url: /v3/api-docs/wallet-service
      - name: Portfolio Service
        url: /v3/api-docs/portfolio-service

