services:
  mysql-db:
    image: mysql:8.0-debian
    container_name: mysql-rkumar
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rkumar
    ports:
      - "9060:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - trading-net

volumes:
  mysql_data:
    
networks:
  trading-net:
    driver: bridge
    name: trading-net
    
#docker network create trading-net